== Common Requirements (applies to both IdP and SP)

=== General

=== Metadata and Trust Management

==== Metadata Content

Metadata MUST NOT contain endpoints that aren't supported.

==== Keys and Certificates in Metadata

Public keys used for encryption and signature verification are bound to certificates in metadata [SAML2Meta].
_(is "bound" the correct verb here?)_

These certificates SHOULD be long-lived and self-signed. To avoid problems with certain non-conforming SAML implementations, certificates in metadata SHOULD NOT be expired.  Certificates in metadata SHOULD be generated from an RSA key with length >= 2048 bits and SHOULD use sha256 or stronger signing algorithms.

IdP metadata MUST include at least one signing certificate.

SP metadata SHOULD include at least one encryption certificate. _(Eric added this)_

When SAML messages are signed, sha256 or stronger signing algorithms SHOULD be used.

==== MDUI Elements

Metadata for SAML entities MUST include UI elements for `<mdui:DisplayName>`, `<mdui:Logo>`, `<mdui:InformationURL>`, and `<mdui:PrivacyStatementURL>`.

The content of the `<mdui:Logo>` element SHOULD be a HTTPS URL and MUST NOT be a HTTP URL.

At least one `<mdui:Logo>` element SHOULD have a `height` attribute of `60` and a `width` attribute of `80`.

An entity MAY include a `<mdui:Logo>` element with a `height` attribute of `16` and a `width` attribute of `16`.

==== Metadata Refresh and Signature Verification

Service Providers and Identity Providers MUST regularly verify their SAML peer configurations by validating them against those peers' current metadata. Metadata used for this configuration validation MUST itself be signed and validated with a key distributed _(verified? validated?)_ separately from the metadata itself.

==== Metadata Signature Verification

_(Suggest merging this section with the one above, as it is odd to split the two sentences above. Alternatively, move second sentence from above to here)_

==== SAML entityIDs

The EntityID of a SAML entity MUST be scoped to the domain of the organization that is the owner of the application, in the case of an SP; or to the domain of the organization whose users are represented by the IdP, in the case of an IdP.

_Specifically, hosted applications must have entityIDs scoped to the client organization's domain, not the hosting organization's domain._

=== Protocol Support

Deployments MUST support the SAML V2.0 Web Browser SSO Profile and MUST support the SAML V2.0 Single Logout Profile as defined in <<SAML2Prof>> and as updated by <<SAML2Err>>. Behavior of deployments MUST be consistent with the requirements of the requirements specified in this deployment profile. 

A deployment indicates support for the SAML V2.0 Web Browser SSO and for the SAML V2.0 Single Logout Profile by including certain browser-facing SSO endpoints in metadata.

=== Clock Skew

Deployers MUST support a minimum of three (3) and a maximum of five (5) minutes of clock skew -- in either direction -- when interpreting `xsd:dateTime` values in assertions and when enforcing security policies based thereupon.

_The following is a non-exhaustive list of items to which this directive applies:_ `NotBefore`, `NotOnOrAfter`, _and_ `validUntil` _XML attributes found on_ `Conditions`, `SubjectConfirmationData`, `LogoutRequest`, `EntityDescriptor`, `EntitiesDescriptor`, `RoleDescriptor`, _and_ `AffiliationDescriptor` _elements._
