== Notation and Terminology

=== References to SAML 2.0 specification

When referring to elements from the SAML 2.0 core specification <<SAML2Core>>, the following syntax is used:

* `<samlp:ProtocolElement>` - for elements from the SAML 2.0 Protocol namespace.
* `<saml:AssertionElement>` - for elements from the SAML 2.0 Assertion namespace.

When referring to elements from the SAML 2.0 metadata specification <<SAML2Meta>>, the following syntax is used:

* `<md:MetadataElement>`

When referring to elements from the Identity Provider Discovery Service Protocol and Profile <<IdPDisco>>, the following syntax is used:

* `<idpdisc:DiscoveryResponse>`

When referring to elements from the SAML 2.0 Metadata Extensions for Login and Discovery User Interface specification <<SAML-Metadata-UI-V1.0>>, the following syntax is used:

* `<mdui:MetadataElement>`

=== Terminology

The abbreviations IdP and SP are used below to refer to Identity Providers and Service Providers in the sense of their usage within the SAML Browser SSO Profile and Single Logout profiles.

Whether explicit or implicit, all the requirements in this document are meant to apply to deployments of SAML profiles and may involve explicit support for requirements by SAML-implementing software and/or supplemental support via application code. Deployments of a Service Provider may refer to both stand-alone implementations of SAML, libraries integrated with an application, or any combination of the two. It is difficult to define a clear boundary between a Service Provider and the application/service it represents, and unnecessary to do so for the purposes of this document.