== SP Requirements

=== Web Browser SSO

SPs MUST support the Browser SSO Profile <<SAML2Prof>>.

==== General Flow

SPs MUST support SP-initiated SSO, i.e., the direct generation of authentication request messages in response to unauthenticated or insufficiently-authenticated access attempts to an application as a whole, or to specific protected content.

SPs MAY support unsolicited responses (so-called IdP-initiated SSO) but MUST NOT require them.

==== Requests

===== Binding

The HTTP-Redirect binding <<SAML2Bind>> MUST be used for the transmission of `<samlp:AuthnRequest>` messages.

Requests MUST NOT be issued inside an HTML frame or via any mechanism that would require the use of third-party cookies by the IdP to establish or recover a session with the User Agent. This will typically imply that requests must involve a full-frame redirect, in order that the top level window origin be associated with the IdP.

===== Request Content

The `<samlp:AuthnRequest>` message MUST either omit the `<samlp:NameIDPolicy>` element (RECOMMENDED), or the element MUST contain an `AllowCreate` attribute of "true" and MUST NOT contain a `Format` attribute.

The `<saml2p:AuthnRequest>` message MUST NOT contain a `<saml2:Subject>` element.

_This is a relatively unused feature that is supported by few IdPs._ 

The message MUST NOT contain an `AssertionConsumerServiceIndex` attribute (i.e., the desired endpoint MUST be the default, or identified via the `AssertionConsumerServiceURL` attribute).

The `AssertionConsumerServiceURL` value MUST match an endpoint location expressed in the SP's metadata exactly, without requiring URL canonicalization/normalization. 

_As an example, the SP MUST NOT use a hostname with port number (such as https://sp.example.no:80/acs) in its request and without (such as https://sp.example.no/acs) in its metadata._

===== Authentication Contexts

An SP that does not require a specific `<saml:AuthnContextClassRef>` value MUST NOT include a `<samlp:RequestedAuthnContext>` element in its requests.

An SP that requires specific `<saml:AuthnContextClassRef>` values MUST specify the allowable values in a `<samlp:RequestedAuthnContext>` element in its requests, with the `Comparison` attribute set to `exact`.

_An SP SHOULD NOT request a `<saml:AuthnContextClassRef>` value in the absence of a shared understanding between itself and the IdP regarding its definition._

==== Responses

===== Binding

SPs MUST support the HTTP-POST binding for the receipt of `<samlp:Response>` messages. Support for other bindings is OPTIONAL.

The endpoint(s) at which an SP supports receipt of `<samlp:Response>` messages MUST be protected by TLS/SSL.

===== XML Encryption

SPs MUST support decryption of `<saml:EncryptedAssertion>` elements. Support for other encrypted constructs is OPTIONAL.

===== Error Handling

SPs MUST gracefully handle error responses containing `<samlp:StatusCode>` other than `urn:oasis:names:tc:SAML:2.0:status:Success`.

The response to such errors MUST direct users to appropriate support resources offered by the SP or alternatively to the `errorURL` attribute in an IdP's metadata.

===== Forced Re-Authentication

SPs that include a `ForceAuthn` attribute of `true` in their requests SHOULD test the currency of the `AuthnInstant` element in the received assertions to verify the currency of the authentication event.

_This is necessary because clients can freely generate requests that do not specify this attribute, potentially bypassing the SP's intent._

==== Subject Identification

===== NameID Formats

SPs MUST support arbitrary `<saml:NameID>` elements regardless of `Format`, for the purposes of Single Logout.

SPs MUST NOT require the presence of a `<saml:NameID>` element and MUST NOT rely on the content of this element for long term identification of subjects;  `<saml:Attribute>` elements MUST be used for this purpose in the manner detailed below.

===== Subject Identifiers

If an SP requires persistent tracking/identification of its users (as most do), then it MUST support one or both of the SAML Attributes defined by <<SAML2SubjId>> for this purpose.

If an SP requires coordination and/or correlation of user activity between itself and other SPs, then the SAML Attribute named `urn:oasis:names:tc:SAML:attribute:subject-id` is appropriate. Otherwise the SAML Attribute named `urn:oasis:names:tc:SAML:attribute:pairwise-id` should be used.

SPs MAY support legacy or historical `<saml:NameID>` and `<saml:Attribute>` content for compatibility reasons but MUST NOT require their use.

===== Subject Identifier Requirements Signaling

An SP MUST represent its identifier requirements in its SAML metadata, consistent with the Requirements Signaling mechanism defined in <<SAML2SubjId>>.

===== Displayable Identifiers

The required identifier types above are opaque, unknown to users in most cases, and unsuitable for display.

SPs requiring the display of identifiers to users, the identification of other users via searching, selection, etc., and similar use cases SHOULD rely on additional suitable SAML Attributes such as:

* `urn:oid:0.9.2342.19200300.100.1.3` (mail)
* `urn:oid:2.16.840.1.113730.3.1.241` (displayName)
* `urn:oid:2.5.4.42` (givenName)
* `urn:oid:2.5.4.4` (sn)

_Note that most such Attributes tend to be defined as multi-valued._

===== Identifier Scoping

SPs MUST prevent unintended identifier collisions in the values asserted by different IdPs, and the required identifier types above are "scoped" via a DNS-like syntax to help fulfill this requirement.

SPs MUST associate identifier scopes with IdPs such that only authorized IdPs may assert identifiers with particular scopes for particular purposes.

_For example, if the `example.com` scope is bound to the IdP named `http://idp.example.com/saml`, it should be generally disallowed for any other IdP to assert an identifier in that scope. Note that this is not a 1:1 relationship; it may frequently happen that multiple IdPs may assert a given scope, or an IdP may assert identifiers in multiple scopes, but the rules for this should be explicit and enforced._

==== Attribute Value Constraints

When consuming SAML Attributes with standardized definitions in external specifications, SPs MUST NOT impose constraints beyond the definitions of those attributes.

_For example, the definition of the `mail` attribute (in SAML, `urn:oid:0.9.2342.19200300.100.1.3`) explicitly allows for multiple values, so an SP that consumes it for some purpose must necessarily allow for that possibility._

==== Deep Linking

Silo-oriented, multi-tenant approaches to cloud application design create an inherent friction with the intended design of the web, user behavior and experience, and the needs of collaboration inherent to many applications. SSO tends to exacerbate these problems and there are important design issues that need to be taken into consideration. These issues, while not strictly speaking a matter of SAML interoperability, have a significant impact on the perception of the system as a whole and on the successful adoption of SSO, regardless of the protocol used.

The web inherently operates on the basis of _addressability_ of resources; that is, users expect to be able to access a piece of information or an application function directly, without regard for their identity, current level of access, or what is convenient for an application developer to support. This leads naturally to the ability to create bookmarks to what matters to them, and users will consistently and understandably route around any attempts to force them through proxies, portals, and other artificial access paths.

At a high level, these issues fall under the term `deep linking`.

_For a wide range of applications in the collaborative space, this notion is not merely convenient, but utterly essential, because such applications presume the sharing of resources with peers between organizations._

For the purposes of the following requirements, we will refer to applications that rely on the exposure of resource URLs that may be shared between users from multiple organizations as "collaborative" applications, even if their purpose may not specifically align with that term.

Applications SHOULD, and collaborative applications MUST, support deep linking. Deep linking implies maintaining support for such links during a Web Browser SSO profile interaction. That is, it SHOULD be possible to request a resource and (authorization permitting) have it supplied as the result of a successful Web Browser SSO profile exchange.

It is RECOMMENDED that SPs support the preservation of POST bodies across a successful SSO profile exchange, subject to size limitations dictated by policy or implementation constraints.

Deep linking implies support for some form of IdP "discovery", the process by which an SP establishes which IdP to use on behalf of a subject. Use of IdP-initiated SSO is a common workaround for supporting discovery, but is incompatible with deep linking, in addition to its other drawbacks.

A common means of discovery is the mapping of resource/application URL (typically virtual host, sometimes path) to a specific IdP. This is strongly discouraged, and disallowed for collaborative applications, since it makes sharing URLs between users from multiple organizations impossible.

SPs SHOULD consider support for the SP Request Initiation Profile and Protocol defined in <<SAML2SPRIP>>, as it provides a general, composable building block, and MAY support other mechanisms and caching solutions (e.g., cookies) as desired, to reduce the frequency of discovery.

===== Support for Multiple IdPs

Related to deep linking, SPs MUST allow for the possibility that any given request requiring authentication may be potentially satisfied by more than one IdP. That is, any scenario in which a piece of content, policy, configuration, or decision on the part of an application is bound to an IdP MUST be constructed in a fashion such that more than one IdP may be so bound.

_This requirement flows from both the inherent requirements of collaborative applications described above, and from the simple reality that enterprises vary in their structure and organization such that any presumed mapping between a contract or set of access policies and a single SAML IdP is inherently constraining. This constraint imposes a need for complex proxying of SSO by many organizations and must be avoided._

=== Single Logout

SPs MAY support the Single Logout Profile <<SAML2Prof>>. The following requirements apply in the presence of such support.

==== Requests

===== Binding

The HTTP-Redirect binding <<SAML2Bind>> MUST be used for the transmission of `<samlp:LogoutRequest>` messages.

SPs MUST support the HTTP-Redirect <<SAML2Bind>> binding for the receipt of `<samlp:LogoutRequest>` messages.

Requests MUST NOT be issued inside an HTML frame or via any mechanism that would require the use of third-party cookies by the IdP to establish or recover a session with the User Agent. This will typically imply that requests must involve a full-frame redirect, in order that the top level window origin be associated with the IdP.

_The full-frame requirement is also necessary to ensure that full control of the user interface is released to the IdP._

===== Request Content

Requests MUST be signed.

The `<saml:NameID>` element included in `<samlp:LogoutRequest>` messages MUST exactly match the corresponding element received from the IdP, including its element content and all XML attributes included therein.

The `<saml:NameID>` element in `<samlp:LogoutRequest>` messages MUST NOT be encrypted.

_The normative requirement for the use of transient identifiers is intended to obviate the need for XML Encryption._

==== Responses

===== Binding

The HTTP-Redirect binding <<SAML2Bind>> MUST be used for the transmission of `<samlp:LogoutResponse>` messages.

SPs MUST support the HTTP-Redirect <<SAML2Bind>> binding for the receipt of `<samlp:LogoutResponse>` messages, in the event that they do not include the `<aslo:Asynchronous>` extension <<SAML2ASLO>> in all of their requests.

===== Response Content

Responses MUST be signed.

==== Behavioral Requirements

SPs MUST terminate a subject's local session before issuing a `<samlp:LogoutRequest>` message to the IdP.

_This ensures the safest possible result for subjects in the event that logout fails for some reason, as it often will._

SPs MUST NOT issue a `<samlp:LogoutRequest>` message as the result of an idle activity timeout.

_Timeout of a single application/service must not trigger logout of an SSO session because this imposes a single service's requirements on an entire IdP deployment. Applications with sensitive requirements should consider other mechanisms, such as the `ForceAuthn` attribute, to achieve their goals._

==== Logout and Virtual Hosting

An SP that maintains distinct sessions across multiple virtual hosts SHOULD identify itself by means of a distinct entityID (with associated metadata) for each virtual host.

_A single entity can have only one well-defined `<SingleLogoutService>` endpoint per binding. Cookies are typically host-based and logout cannot typically be implemented easily across virtual hosts. Unlike during SSO, a `<samlp:LogoutRequest>` message cannot specify a particular response endpoint, so this scenario is generally not viable._

=== Metadata and Trust Management

==== Support for Multiple Keys

SP deployments MUST support multiple signing certificates in IdP metadata and MUST support validation of XML signatures using a key from any of them.

SP deployments MUST be able to support multiple decryption keys and MUST be able to decrypt `<saml:EncryptedAssertion>` elements encrypted with any configured key.

_These requirements make seamless key migration possible for both parties._

==== Metadata Content

By virtue of this profile's requirements, an SP's metadata MUST contain:

* an `<md:SPSSODescriptor>` role element
** at least one `<md:AssertionConsumerService>` endpoint element
** at least one `<md:KeyDescriptor>` element whose `use` attribute is omitted or set to `signing`
** at least one `<md:KeyDescriptor>` element whose `use` attribute is omitted or set to `encryption`
* an `<md:Extensions>` element
** an `<mdui:UIInfo>` extension element with previously prescribed content
** an `<mdattr:EntityAttributes>` extension element with previously prescribed content

In addition, an SP's metadata MUST contain:

* an `<md:ContactPerson>` element with a `contactType` of `technical` and an `<md:EmailAddress>` element

An `<md:SingleLogoutService>` element MAY be omitted in the event that an SP either does not support the Single Logout Profile, or solely issues `<samlp:LogoutRequest>` messages containing the `<aslo:Asynchronous>` extension <<SAML2ASLO>>.
