= SAML V2.0 Implementation Profile for Federation Interoperability Version 1.0
:numbered:
:toc:
:toc-placement: preamble
:docinfo:
:notitle:
:nofooter:

// did not manage to CSS-select the top-level title: instead using :notitle: plus following pass-though
++++
<h1 style="color: blue; text-align: center; font-size: 150%; margin-bottom: 2em; font-weight: bold;">
  SAML V2.0 Implementation Profile for Federation Interoperability
</h1>
++++

[horizontal]
Version:: 1.0
Date:: 2018-04-18
Location:: https://docs.kantarainitiative.org/fi/wg/rec-saml2-implementation-profile-for-fedinterop.html
Status:: This document is a Kantara Initiative Recommendation produced by the https://kantarainitiative.org/confluence/display/fiwg/Home[Federation Interoperability Work Group]. It has been approved by the Membership of the Kantara Initiative. See the Kantara Initiative https://kantarainitiative.org/confluence/download/attachments/2293776/Kantara%20Operating%20Procedures%20V2.0-20150226.pdf?version=2&modificationDate=1444240055000&api=v2[Operating Procedures] for more information.

include::contributors.adoc[]

.Abstract
This document encompasses a set of software conformance requirements intended to facilitate interoperability within the context of full mesh identity federations, such as those found in the research and education sector. It attempts to address a number of common barriers to interoperability and details features that are necessary in order to use SAML metadata as a foundation for scalable trust fabrics. It supercedes the link:eGovImplProfile.html[eGovernment Implementation Profile V2.0bis] from June 2011.

.Copyright Notice
SAML v2.0 Implementation Profile for Federation Interoperability ©2017 Internet2 and/or the respective contributors, used under license.  All rights reserved.

.License
This work is licensed under the https://creativecommons.org/licenses/by-sa/3.0/us/[Creative Commons Attribution-ShareAlike 3.0 United States License].

== Introduction
The material contained herein is intended for use by implementers of SAML software. It does not specify a fixed set of behaviors for all deployments or limit in any way the features that can be provided in a given implementation, but rather serves as a complement to deployment profiles by identifying a standard set of software capabilities necessary for scalable federation. This profile can form the basis for testing frameworks capable of providing for the validation of conformant software packages.

include::notation.adoc[]

== Common Requirements

include::general.adoc[]

include::metadata-trust.adoc[]

include::messages.adoc[]

include::extensibility.adoc[]

include::algorithms.adoc[]

include::sp.adoc[]

include::idp.adoc[]

include::references.adoc[]
