= SAML V2.0 Implementation Profile for Federation Interoperability
:numbered:
:toc:

:toc!:

.Abstract
This document encompasses a set of software conformance requirements intended to facilitate interoperability within the context of full mesh identity federations, such as those found in the research and education sector. It attempts to address a number of common barriers to interoperability and details features that are necessary in order to use SAML metadata as a foundation for scalable trust fabrics.

.Status
In transition from InCommon FI-WG to Kantara FI-WG

== Introduction
The material contained herein is intended for use by implementers of SAML software. It does not specify a fixed set of behaviors for all deployments or limit in any way the features that can be provided in a given implementation, but rather serves as a complement to deployment profiles (such as the Kantara SAML2int profile <<SAML2int>>) by identifying a standard set of software capabilities necessary for scalable federation. This profile can form the basis for testing frameworks capable of providing for the validation of conformant software packages.

include::notation.adoc[]

== Common Requirements

include::metadata-trust.adoc[]

include::general.adoc[]

include::messages.adoc[]

include::extensibility.adoc[]

include::algorithms.adoc[]

include::sp.adoc[]

include::idp.adoc[]

include::references.adoc[]

include::contributors.adoc[]

include::egov-profile-diff.adoc[]
